# Base image for executing Python scripts
FROM python:latest

# Set working directory
WORKDIR /app

# Command to execute a Python script
# Assumes the Python file is provided as 'main.py'
CMD ["python", "main.py"]
