# Base image for executing Node.js scripts
FROM node:latest

# Set working directory
WORKDIR /app

# Command to execute a Node.js script
# Assumes the Node.js file is provided as 'main.js'
CMD ["node", "main.js"]
